name: Build and push backend Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:  # Build on source code, dependencies, or Dockerfile change
      - "backend/src/**.py"
      - "backend/uv.lock"
      - "backend/pyproject.toml"
      - "backend/Dockerfile"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ggoncalves17/digital-twin:latest

    deploy-render:
      needs: build-and-push-image
      on: ubunutu-latest
      steps:
          - name: Invoke deployment hook
            run: |
              curl -X GET ${{secrets.DEPLOY_URL}}
